[package]
name = "brainrot-machine"
version = "0.1.0"
edition = "2024"

[dependencies]
rustautogui = "2.5.0"
tao = "0.34.3"
windows = { version = "0.62.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
wry = "0.53.3"
x-win = "5.3.0"
